spring.application.name=catalog
server.port=8080
rate-limit.enabled=true
rate-limit.rpm=10
rate-limit.algo=fixed
datasource.type=spotify_api
SpotifyAPIDataSources.token=BQC1z__0N9zvHwWQ8pUidAhFzv4CFiP6rHWEZKo-irDOKEJmVTxrd79gICkTI03RTyFkw_UtGilDzF-EOBYEHmGmvRYMzSDiZrXS9WllYFDBNG00wUEULPTjk3oKLT1Acu3ShCuuU-g
jsonDataSourceService.data=data-tests
