spring.application.name=catalog
server.port=8080
rate-limit.enabled=true
rate-limit.rpm=10
rate-limit.algo=fixed
datasource.type=spotify_api
jsonDataSourceService.data=data-tests
spotify.client.id=ce5db3553cfd4a03a0c71e1d3aa4f58d
spotify.client.secret=64cc16d207b146a4942d9d833953b53c
spotify.api.url=https://api.spotify.com/v1
SpotifyAPIDataSources.token=BQAgB9iUzuPZ1lgvD94jXaMfBNWrz_2HKv_X_UgpCv7FM1D_szJBIt7OhX4ZzJd4eIopAInIm_X5reI8KdVSAKZOeEmQIvxe2XSAQsWCjkq2HfOCztgLr3gG7YlYFkty8L35jFjFQ6o