name: SpotifyCatalogAPI tests

on:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  BuildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: |
          mvn test -q -Dtest=CatalogUtilsTest,SpotifyUtilsTest
          mvn surefire-report:report-only 

      - name: Check Styles
        run: |
          mvn checkstyle:check -Dcheckstyle.violationSeverity=warning

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit


  TriggerUITests:
    name: Trigger UI Testing Workflow
    runs-on: ubuntu-latest
    needs: BuildAndTest
    env:
      SPOTIFY_TESTING_REPO_NAME: ahmadnas00/SpotifyTesting
      UI_TESTING_WORKFLOW_ID: ui_testing.yaml
    steps:
      - name: Trigger Selenium Testing Workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"ref\": \"main\", \"inputs\": {\"browser\": \"chrome\"}}" \
            https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
